In [1]:
import numpy as np

In [33]:
a = np.array([2,1,-1,0,0])
b = np.array([0,0,2,1,-1]) 

In [38]:
def xcorrelate(a,b,lag):
    m = len(a)
    n = len(b)
    k = len(a)+len(b)-1
    a = a[::-1]
    c = np.zeros((k))
    C = {}
    for i in range(k):
        for j in range(n-lag):
            if (i-j>=0 and i-j<m ):
                c[i]+=a[i-j]*b[j+lag]
            else:
                continue
        C[str(i-(m-1))] = c[i]
    return c,C

In [46]:
c,C=xcorrelate(a,a,0)
print(c)
print(C)

[ 0.  0. -2.  1.  6.  1. -2.  0.  0.]
{'-4': 0.0, '-3': 0.0, '-2': -2.0, '-1': 1.0, '0': 6.0, '1': 1.0, '2': -2.0, '3': 0.0, '4': 0.0}


In [48]:
c,C=xcorrelate(a,b,4)
print(c)
print(C)

[ 0.  0.  0.  0. -2.  1.  6.  1. -2.]
{'-4': 0.0, '-3': 0.0, '-2': 0.0, '-1': 0.0, '0': -2.0, '1': 1.0, '2': 6.0, '3': 1.0, '4': -2.0}


In [41]:
np.correlate(a,a, "full")

array([ 0,  0, -2,  1,  6,  1, -2,  0,  0])

In [7]:
np.correlate(b,a, "full")

array([ 0,  0,  0,  0, -2,  1,  6,  1, -2])